### ISSUE TITLE
Add a license to the project

### ISSUE THREAD

**Issue by itaisteinherz** [itaisteinherz/neo4j-browser#17]

**Comment by Pratik151** [comment]
@itaisteinherz which license you want to be added for project? GNU or Apache or MIT or any other?

**Comment by ajzawawi** [comment]
@itaisteinherz I added an MIT license in my PR. Let us know if you want a different license.

**Comment by itaisteinherz** [comment]
@Pratik151 I want to add the Apache License 2.0 to the project. Also, it would be great if you could add a reference to the license in the package.json file.

**Comment by ajzawawi** [comment]
@itaisteinherz I'll edit it in my PR and add to package.json

**Comment by itaisteinherz** [comment]
@ajzawawi Please look at my comments for your PR (#18). Also, please rename the title of the PR to an appropriate title.
